INSERT INTO vehicle_types (id, type) VALUES
(1, 'Batea'),
(2, 'Carroceria'),
(3, 'Cava'),
(4, 'Chasis'),
(5, 'Colectivo'),
(6, 'Coupe'),
(7, 'Encava'),
(8, 'Enduro'),
(9, 'Estacas'),
(10, 'Furgon'),
(11, 'Granel'),
(12, 'Hact Bach'),
(13, 'Jaula'),
(14, 'Minibus'),
(15, 'Minivan'),
(16, 'Motocicleta'),
(17, 'Panel'),
(18, 'Paseo'),
(19, 'Pick-Up'),
(20, 'Pick-Up D / Cabina'),
(21, 'Pick-Up / Baranda / Hierro'),
(22, 'Pick-Up / C Furgon'),
(23, 'Plat / Estruc / Hierro'),
(24, 'Plataforma'),
(25, 'Platf / Baranda'),
(26, 'Platf / Estaca'),
(27, 'Racing'),
(28, 'Renegado'),
(29, 'Rustico Carga'),
(30, 'Scooter'),
(31, 'Sedan'),
(32, 'Sport Wagon'),
(33, 'Tanque'),
(34, 'Techo Duro'),
(35, 'Utilitario'),
(36, 'Volteo'),
(37, 'Casillero');


